"""empty message

Revision ID: 2ef3ff74cb5c
Revises: 056b6c9af5e3
Create Date: 2017-09-03 22:58:38.814000

"""

# revision identifiers, used by Alembic.
revision = '2ef3ff74cb5c'
down_revision = '056b6c9af5e3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity', 'terms',
               existing_type=mysql.VARCHAR(length=2048),
               type_=sa.String(length=4096),
               existing_nullable=True)
    op.create_foreign_key(None, 'auction_purchase', 'participant', ['participant_id'], ['id'])
    op.create_foreign_key(None, 'auction_purchase', 'activity', ['activity_id'], ['id'])
    op.add_column('participant', sa.Column('barcode', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'participant', 'activity', ['activity_id'], ['id'])
    op.create_foreign_key(None, 'product', 'activity', ['activity_id'], ['id'])
    op.create_foreign_key(None, 'purchase', 'product', ['product_id'], ['id'])
    op.create_foreign_key(None, 'purchase', 'participant', ['participant_id'], ['id'])
    op.create_foreign_key(None, 'purchase', 'activity', ['activity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase', type_='foreignkey')
    op.drop_constraint(None, 'purchase', type_='foreignkey')
    op.drop_constraint(None, 'purchase', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, 'participant', type_='foreignkey')
    op.drop_column('participant', 'barcode')
    op.drop_constraint(None, 'auction_purchase', type_='foreignkey')
    op.drop_constraint(None, 'auction_purchase', type_='foreignkey')
    op.alter_column('activity', 'terms',
               existing_type=sa.String(length=4096),
               type_=mysql.VARCHAR(length=2048),
               existing_nullable=True)
    # ### end Alembic commands ###
