"""empty message

Revision ID: 251bd70371aa
Revises: badb776d038b
Create Date: 2017-09-08 00:40:02.834000

"""

# revision identifiers, used by Alembic.
revision = '251bd70371aa'
down_revision = 'badb776d038b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.execute('ALTER TABLE activity ENGINE = InnoDB;')
    op.execute('ALTER TABLE auction_purchase ENGINE = InnoDB;')
    op.execute('ALTER TABLE participant ENGINE = InnoDB;')
    op.execute('ALTER TABLE product ENGINE = InnoDB;')
    op.execute('ALTER TABLE purchase ENGINE = InnoDB;')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.execute('ALTER TABLE activity ENGINE = MyISAM;')
    op.execute('ALTER TABLE auction_purchase ENGINE = MyISAM;')
    op.execute('ALTER TABLE participant ENGINE = MyISAM;')
    op.execute('ALTER TABLE product ENGINE = MyISAM;')
    op.execute('ALTER TABLE purchase ENGINE = MyISAM;')
